version: 2.1
orbs:
  common: jsight/common-ci@1.3.5

parameters:
  go-version:
    type: string
    default: '1.18'

workflows:
  qa:
    jobs:
      - common/go-test: &common-params
          context: online-editor-development
          go-version: << pipeline.parameters.go-version >>

      - common/go-lint:
          <<: *common-params