// Autogenerated code!
// DO NOT EDIT!
//
// Generated by OrderedMap generator from the internal/cmd/generator command.

package directive

import (
	"bytes"
	"encoding/json"
)

// Set sets a value with specified key.
func (m *Directives) Set(k string, v *Directive) {
	m.mx.Lock()
	defer m.mx.Unlock()

	if m.data == nil {
		m.data = map[string]*Directive{}
	}
	if !m.has(k) {
		m.order = append(m.order, k)
	}
	m.data[k] = v
}

// Update updates a value with specified key.
func (m *Directives) Update(k string, fn func(v *Directive) *Directive) {
	m.mx.Lock()
	defer m.mx.Unlock()

	if !m.has(k) {
		// Prevent from possible nil pointer dereference if map value type is a
		// pointer.
		return
	}

	m.data[k] = fn(m.data[k])
}

// GetValue gets a value by key.
func (m *Directives) GetValue(k string) *Directive {
	m.mx.RLock()
	defer m.mx.RUnlock()

	return m.data[k]
}

// Get gets a value by key.
func (m *Directives) Get(k string) (*Directive, bool) {
	m.mx.RLock()
	defer m.mx.RUnlock()

	v, ok := m.data[k]
	return v, ok
}

// Has checks that specified key is set.
func (m *Directives) Has(k string) bool {
	m.mx.RLock()
	defer m.mx.RUnlock()

	return m.has(k)
}

func (m *Directives) has(k string) bool {
	_, ok := m.data[k]
	return ok
}

// Len returns count of values.
func (m *Directives) Len() int {
	m.mx.RLock()
	defer m.mx.RUnlock()

	return len(m.data)
}

// Iterate iterates over map key/values.
// Will block in case of slow consumer.
// Should be used only for read only operations. Attempt to change something
// inside loop will lead to dead lock.
// Use Directives.Map when you have to update value.
func (m *Directives) Iterate() <-chan DirectivesItem {
	ch := make(chan DirectivesItem)
	go func() {
		m.mx.RLock()
		defer m.mx.RUnlock()

		for _, k := range m.order {
			ch <- DirectivesItem{
				Key:   k,
				Value: m.data[k],
			}
		}
		close(ch)
	}()
	return ch
}

// Map iterates and changes values in the map.
func (m *Directives) Map(fn mapDirectivesFunc) error {
	m.mx.Lock()
	defer m.mx.Unlock()

	for _, k := range m.order {
		v, err := fn(k, m.data[k])
		if err != nil {
			return err
		}
		m.data[k] = v
	}
	return nil
}

type mapDirectivesFunc = func(k string, v *Directive) (*Directive, error)

// DirectivesItem represent single data from the Directives.
type DirectivesItem struct {
	Key   string
	Value *Directive
}

var _ json.Marshaler = &Directives{}

func (m *Directives) MarshalJSON() ([]byte, error) {
	m.mx.RLock()
	defer m.mx.RUnlock()

	var buf bytes.Buffer
	buf.WriteRune('{')

	for i, k := range m.order {
		if i != 0 {
			buf.WriteRune(',')
		}

		// marshal key
		key, err := json.Marshal(k)
		if err != nil {
			return nil, err
		}
		buf.Write(key)
		buf.WriteRune(':')

		// marshal value
		val, err := json.Marshal(m.data[k])
		if err != nil {
			return nil, err
		}
		buf.Write(val)
	}

	buf.WriteRune('}')
	return buf.Bytes(), nil
}
